SI-8177, SI-3425 et al prefixes going wrong
baseTypeIndex uses binary search, which depends on certain
attributes of the sequence being searched. In particular, it
depends on there being no equal elements among the sequence
being searched. This invariant was not maintained, leading to
the search failing to find matching types.

The intention is that every type in a BaseTypeSeq has a distinct
typeSymbol. I made this true by intercepting when two types with
the same typeSymbol were being placed into a base type sequence,
and rather than letting them both in, intersecting them.

At this point there's one failure, pos/t7688.scala.

t7688.scala:6: error: no type parameters for constructor A: (position: C#Position)A[C] exist so that it can be applied to arguments (c.universe.Position)
 --- because ---
argument expression's type is not compatible with formal parameter type;
 found   : c.universe.Position
 required: ?C#Position
    (which expands to)  Aliases.this.universe.Position
  def apply(c: Context)(in: c.Tree): A[c.type] = new A(in.pos)
                                                 ^
t7688.scala:6: error: type mismatch;
 found   : c.universe.Position
 required: C#Position
    (which expands to)  C#universe.Position
  def apply(c: Context)(in: c.Tree): A[c.type] = new A(in.pos)
                                                          ^
two errors found