SI-6502 More robust REPL :require
  - handle missing files gracefully (rather than NPE)
  - read the class name with ASM, rather than with a dummy
    classloader. The dummy classloader is prone to throwing
    `LinkageError`s, as reported in the comments of SI-6502.

Manual test of the original report:

```
% qscala
Welcome to Scala version 2.11.5-20150115-183424-155dbf3fdf (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_25).
Type in expressions to have them evaluated.
Type :help for more information.

scala> :require does/not/exist
Cannot read: does/not/exist

scala> classOf[org.junit.Test]
<console>:8: error: object junit is not a member of package org
              classOf[org.junit.Test]
                          ^

scala> :require /Users/jason/.m2/repository/junit/junit/4.11/junit-4.11.jar
Added '/Users/jason/.m2/repository/junit/junit/4.11/junit-4.11.jar' to classpath.

scala> classOf[org.junit.Test]
res1: Class[org.junit.Test] = interface org.junit.Test
```

I have commited an automated test that is a minimization of this one.