REPL checks for fatal parse warnings
Previously, user input was re-parsed embedded in a template.
Also strip the marker for extended explanations.

```
scala> List(1) map (42 +) ; List(1) map (42 +)
                       ^
       error: postfix operator + needs to be enabled
       by making the implicit value scala.language.postfixOps visible.
       This can be achieved by adding the import clause 'import
scala.language.postfixOps'
       or by setting the compiler option -language:postfixOps.
       See the Scaladoc for value scala.language.postfixOps for a
discussion
       why the feature needs to be explicitly enabled.
                                            ^
       error: postfix operator + needs to be enabled
       by making the implicit value scala.language.postfixOps visible.

scala> def f() { }
               ^
       warning: procedure syntax is deprecated: instead, add `: Unit =`
to explicitly declare `f`'s return type
error: No warnings can be incurred under -Xfatal-warnings.

scala>
```