Fix some tests, move others to pending/
Move run/t8960 to pending

It tests the serialVersionUID field on closure classes. The field
doesn't exist for indyLambda closures.

See https://issues.scala-lang.org/browse/SI-9373

Move some reify tests to pending

They fail at runtime in GenBCode since scala is built with indyLambda
enabled:

java.lang.AssertionError: assertion failed: Bad superClass for trait JFunction1: class Any
  at scala.tools.nsc.Global.assert(Global.scala:261)
  at scala.tools.nsc.backend.jvm.BTypesFromSymbols.setClassInfo(BTypesFromSymbols.scala:228)

Noted in https://issues.scala-lang.org/browse/SI-9374

force t6546 to GenASM - no closure elimination in GenBCode yet

Noted in https://issues.scala-lang.org/browse/SI-9364.

Fix or disable some tests that fail because of the old optimizer

The old inliner fails more often when the library is built with
indylambda.

Noted in https://issues.scala-lang.org/browse/SI-9374.

Example: List.foreach

➜  sandbox git:(jfun) ✗ qs -Ybackend:GenASM -optimize -Yinline-warnings
Welcome to Scala version 2.12.0-20150630-220939-1cb032d806 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_45).
Type in expressions to have them evaluated.
Type :help for more information.

scala> List(1,2,3).foreach(x => x + 1)
<console>:11: warning: Could not inline required method foreach because bytecode unavailable.
       List(1,2,3).foreach(x => x + 1)
                          ^
<console>:11: warning: At the end of the day, could not inline @inline-marked method foreach
       List(1,2,3).foreach(x => x + 1)
                          ^

Upate a number of tests for having indyLambda enabled

The delambdafyLambdaClassNames tests was removed, there's nothing to
tests with indyLambda.