Move some reify tests to pending
They fail at runtime in GenBCode since scala is built with indyLambda
enabled:

java.lang.AssertionError: assertion failed: Bad superClass for trait JFunction1: class Any
  at scala.tools.nsc.Global.assert(Global.scala:261)
  at scala.tools.nsc.backend.jvm.BTypesFromSymbols.setClassInfo(BTypesFromSymbols.scala:228)

Noted in https://issues.scala-lang.org/browse/SI-9374