Merged revisions 24830-24831,24834-24862 via sv...
Merged revisions 24830-24831,24834-24862 via svnmerge from
https://lampsvn.epfl.ch/svn-repos/scala/scala/trunk

........
  r24830 | extempore | 2011-04-26 21:00:24 +0200 (Tue, 26 Apr 2011) | 1 line

  Some solid progress on the pattern matcher, no review. ........ r24831
| odersky | 2011-04-27 12:26:39 +0200 (Wed, 27 Apr 2011) | 1 line

  More bridges in collections. Review by prokopec.
........
  r24834 | extempore | 2011-04-27 20:35:47 +0200 (Wed, 27 Apr 2011) | 1 line

  Fixed inversion of fsc's exit code, closes #4519 no review. ........
r24835 | extempore | 2011-04-27 20:36:04 +0200 (Wed, 27 Apr 2011) | 2
lines

  Fixed a booch I made in io.Position's positioning. Closes #4498, no
review. ........ r24836 | extempore | 2011-04-27 20:36:16 +0200 (Wed, 27
Apr 2011) | 1 line

  A little cleanup on a repl command, no review.
........
  r24837 | extempore | 2011-04-27 20:36:32 +0200 (Wed, 27 Apr 2011) | 5 lines

  Trying to fix the pattern matcher took me into the lambda lifter,
and I made some changes which seemed sensible to me. I'm going to be a
stickler about eliminating mutable maps which hold mutable listbuffers.
I could use some confirmation that I didn't somehow break the world:
review by dragos. ........ r24838 | extempore | 2011-04-27 20:36:47
+0200 (Wed, 27 Apr 2011) | 4 lines

  Trying out a different strategy for restoring terminal settings so we
don't have a list of hardcoded terminal types. Now it saves the terminal
settings on script start and restores those on exit. Closes #4170,
review by rytz. ........ r24839 | extempore | 2011-04-28 01:49:27 +0200
(Thu, 28 Apr 2011) | 1 line

  Cleaned up some hopelessly atrophied documentation, no review.
........ r24840 | extempore | 2011-04-28 03:10:22 +0200 (Thu, 28 Apr
2011) | 4 lines

  Upgraded -d so you can output classes directly to a jar. Very (very)
loosely based on a patch from dmharrah. Like dmharrah before me, I
see little if any change in compile times, which I find difficult to
explain. Closes #27, review by dmharrah. ........ r24841 | extempore |
2011-04-28 17:12:42 +0200 (Thu, 28 Apr 2011) | 5 lines

  Improvements to the AST browser contributed by Yuvi Masory. Uses
Nimbus LAF when available and improves readability by padding
components. Adds menu items and key bindings for expanding and
contracting nodes, closing the browser and continuing compilation, and
closing the browser and aborting. No review. ........ r24842 | extempore
| 2011-04-28 18:23:45 +0200 (Thu, 28 Apr 2011) | 15 lines

  Improved the error message for another of the most common situations
  I hear about in newbieland. It could be taken further. If compilation
  fails due to an unimplemented abstract method, and there is a concrete
  method of the same name and arity, it will do a pairwise analysis of
  the parameters and attempt to further explain where you went off the
  beam if it feels it can do so sensibly. Such as in the test case:

    % scalac S.scala
    S.scala:1: error: class S needs to be abstract, since method g in class J of type (y: Int,z: java.util.List)Int is not defined
    (Note that java.util.List does not match java.util.List[String]. To implement a raw type, use java.util.List[_])
    class S extends J {
          ^
    one error found

  No review.
........
  r24843 | extempore | 2011-04-28 18:26:05 +0200 (Thu, 28 Apr 2011) | 11 lines

  I wrote a warning when nullary methods return Unit. I wimped out of
  including it in this patch because we had about 200 of them, and
  that's what is fixed in this patch. I will add the warning to some
  kind of "-Xlint" feature after 2.9.

  This is motivated at least partly by the resolution of #4506, which
indicates the distinction between "def foo()" and "def foo" will
continue to jab its pointy stick into our eyes, so I believe we have a
minimal duty of at least following our own advice about what they mean
and not making a semirandom choice as to whether a method has parens
or not. Review by community. ........ r24844 | odersky | 2011-04-29
13:07:56 +0200 (Fri, 29 Apr 2011) | 1 line

  Fixes #4525. No review.
........
  r24845 | plocinic | 2011-04-29 16:27:35 +0200 (Fri, 29 Apr 2011) | 1 line

  remove now redundant check (see #4426). review by extempore ........
r24846 | plocinic | 2011-04-29 16:27:40 +0200 (Fri, 29 Apr 2011) | 1
line

  Closes #4457. Review by odersky
........
  r24847 | odersky | 2011-04-29 17:35:37 +0200 (Fri, 29 Apr 2011) | 1 line

  Ignore type errors raised in later phases that are due to mismatching
existentials. Quick fix to address lift build failures. Review by
dragos. ........ r24848 | odersky | 2011-04-29 18:02:53 +0200 (Fri, 29
Apr 2011) | 1 line

  Second version of trying to avoid the lift crasher bug. ........
r24849 | odersky | 2011-04-29 18:13:31 +0200 (Fri, 29 Apr 2011) | 1 line

  Issuing warnings with detailed info when we encounter the lift crasher
case. ........ r24850 | michelou | 2011-04-29 21:41:12 +0200 (Fri, 29
Apr 2011) | 2 lines

  removed legacy library code (package scala.mobile) ........ r24851 |
extempore | 2011-04-29 22:13:10 +0200 (Fri, 29 Apr 2011) | 4 lines

  Fixing the pattern matcher regression I introduced between rc1 and
rc2. Not done with this situation but at least I managed to boil out
the big problem and keep my five closed pattern matcher tickets to
boot. Closes #4523, no review. ........ r24852 | extempore | 2011-04-30
00:40:03 +0200 (Sat, 30 Apr 2011) | 1 line

  Making further unapply regressions less likely, no review. ........
r24853 | extempore | 2011-04-30 22:00:39 +0200 (Sat, 30 Apr 2011) | 3
lines

  After having to update the code for someone else, ran damarau
levenshtein on trunk again. Patchwise, I guess correcting spelling
errors in comments is about as safe as it gets. No review. ........
r24854 | extempore | 2011-04-30 22:01:00 +0200 (Sat, 30 Apr 2011) | 1
line

  Don't crash the pickler with erroneous types. Review by odersky.
........ r24855 | extempore | 2011-04-30 22:01:25 +0200 (Sat, 30 Apr
2011) | 4 lines

  Completely to my surprise, found that fixing all those sequence issues
revealed that the pattern matcher can catch a lot more inexhaustive
cases than it has been catching. Fixed most of the inexhaustive matches
in the compiler, which had become a bit warnier. No review. ........
r24856 | extempore | 2011-04-30 22:01:48 +0200 (Sat, 30 Apr 2011) | 2
lines

  A few minor cleanups involving logging messages, assertion messages,
compiler warnings, and other innocuous matters. No review. ........
r24857 | extempore | 2011-05-01 07:10:09 +0200 (Sun, 01 May 2011) | 2
lines

  Don't issue a deprecation warning if the deprecated method is being
called from a bridge method. No review. ........ r24858 | extempore |
2011-05-01 07:10:58 +0200 (Sun, 01 May 2011) | 4 lines

  Since I don't want to commit anything "interesting" until we ship 2.9,
a few uninteresting cleanups involving how types are printed, getting
some debugging code in shape to prepare for the long winter ahead, etc.
No review. ........ r24859 | extempore | 2011-05-01 07:43:05 +0200 (Sun,
01 May 2011) | 2 lines

  Realized how noisy the @deprecated-takes-two-arguments message was and
quieted it down. Oh, and documented the arguments. No review. ........
r24860 | extempore | 2011-05-01 20:15:49 +0200 (Sun, 01 May 2011) | 7
lines

  Reducing the sbt launcher footprint by eliminating val references
which go through the scala package object, since they lead to
otherwise unnecessary classes becoming required at startup. Mostly
this means library files with constructors like "Iterator.empty" or
"Stream.continually" receive a direct import of that companion. The one
slightly less than cosmetic change was moving the strange xml value
"$scope" back into Predef, because otherwise I have to touch the xml
code generation. No review. ........ r24861 | extempore | 2011-05-01
21:58:44 +0200 (Sun, 01 May 2011) | 2 lines

  Added a @bridge'd $scope back to scala package object for binary
compat. No review. ........ r24862 | extempore | 2011-05-02 05:28:58
+0200 (Mon, 02 May 2011) | 4 lines

  Figuring it couldn't hurt if more people had a command of some of
our binary compatibility impacting code, I went over the ModuleDef
elimination with my clarify stick and made the machinery more
transparent, to me anyway. Review by plocinic. ........