Add -h abbreviation to scaladoc help.
I've never used scaladoc cli before so tonight I downloaded it and the
first thing I tried was:

```
❯ scaladoc -h
scaladoc error: bad option: '-h'
  scaladoc -help  gives more information
error: IO error while decoding -h with UTF-8: -h (No such file or directory)
Please try specifying another one using the -encoding option
```

This is great that it then tells you to use `-help`, but I'm always
slightly annoyed when cli tools don't just default all `-help`,
`--help`, and `-h` to help. So if this doesn't conflict with anything
else (and looking I didn't see that it does), would it be alright to
also have `-h` as an abbreviation for `-help`?