Resurrect a test for type inference
This test was removed in ... when case class extension was disallowed.
But the intent of the test was actually to exercise a path through
type inference, described in `Infer#exprTypeArgs`.

When I remove that special case, the test still fails:

```
test/files/pos/jesper.scala:29: error: No implicit view available from Pair.Cons[Int,Pair.Cons[Boolean,Pair.End]] => Boolean.
 val x2 : Boolean = p.find[Boolean]  // Doesn't compile
                          ^
one error found
```

This special case is important to understand when deciphering
the inference in this program:

```
object Test {

  trait Cov[+A]
  def cov[A](implicit ev: Cov[A]): A = ???
  implicit def covImp[A]: Cov[A] = ???

  trait Inv[A]
  def inv[A](implicit ev: Inv[A]): A = ???
  implicit def invImp[A]: Inv[A] = ???

  trait Con[-A]
  def con[A](implicit ev: Con[A]): A = ???
  implicit def conImp[A]: Con[A] = ???

  cov : String // (Test.this.cov[String](Test.this.covImp[Nothing]): String);
               // (Test.this.cov[Nothing](Test.this.covImp[Nothing]): String) (or, without the special case in exprTypeArgs)
  inv : String // (Test.this.inv[Nothing](Test.this.invImp[Nothing]): String);
  con : String // (Test.this.con[Any](Test.this.conImp[Any]): String)
}
```