SI-8219 Pending test case for unpositioned implicit error
Extracted with tweezers from ScalaTest and Scalacheck implicits.

    % scalac-hash v2.11.0-M7 test/pending/pos/t8219.scala
    error: type mismatch;
     found   : Any
     required: AnyRef
    Note: Any is not implicitly converted to AnyRef.  You can safely
    pattern match `x: AnyRef` or cast `x.asInstanceOf[AnyRef]` to do so.
    error: type mismatch;
     found   : Any
     required: AnyRef
    Note: Any is not implicitly converted to AnyRef.  You can safely
    pattern match `x: AnyRef` or cast `x.asInstanceOf[AnyRef]` to do so.
    two errors found