Based on the frequency with which I hear questi...
Based on the frequency with which I hear questions about it and similar,
this error message assumes too much understanding.

  scala> scala.collection.mutable.MultiMap(1, 2, 3) <console>:8: error:
  value MultiMap is not a member of package scala.collection.mutable

Now it says:

  scala> scala.collection.mutable.MultiMap(1, 2, 3) <console>:8: error:
  object MultiMap is not a member of package scala.collection.mutable
  Note: trait MultiMap exists, but it has no companion object.

No review.