SI-1994 Test case for fixed overriding problem
The test case passes since Scala 2.9.2.

Prior, it failed with:

	~/scala/2.9.1/bin/scalac sandbox/t1994.scala
	sandbox/t1994.scala:9: error: method y overrides nothing
	  override def y = 1
	               ^
	one error found