fix t9400 test with JDK9+
```
t9400.scala:2: error: class Deprecation needs to be abstract, since:
it has 2 unimplemented members.
/** As seen from class Deprecation, the missing signatures are as follows.
 *  For convenience, these are usable as stub implementations.
 */
  def forRemoval(): Boolean = ???
  def since(): String = ???

class Deprecation extends Deprecated {
      ^
one error found
```