[mergeforward] Avoid leaking constraints between typechecking implicit candidates
  - Predicate the backport of the optimization to avoid expensive
    type error creation to -Xsource:2.13, because side effects in
    explainVariance can be witnessed in type variables in the pt
    of an in-progress implicit search.
  - Fix this side-effect leakage with judicious use of undoLog
    around implicit candidate type checking, again under
    -Xsource:2.13 for bug compatibility.

I haven't managed to get a standalone test case, I've been using Specs2
with:

```
import org.specs2.matcher.{Matcher, ValueCheck, OptionLikeCheckedMatcher, OptionLikeMatcher}

trait Disj[A, B]
class Repro {
  def returnValue[T](check: ValueCheck[T]): Any = null
  implicit def matcherIsValueCheck[T](m: Matcher[T]): ValueCheck[T] = ???

  def overloaded[T](t: ValueCheck[T]): LeftDisjunctionCheckedMatcher[T] = null
  def overloaded[T]: OptionLikeMatcher[({type l[a]= Disj[a, _]})#l, T, T] = null
  trait LeftDisjunctionCheckedMatcher[T] extends OptionLikeCheckedMatcher[({type l[a]=Disj[a, _]})#l, T, T]

  returnValue(overloaded(null: Matcher[AnyRef]))
}

```

Which fails to compile with the bug fix:

```
/Users/jz/code/specs2/scalaz/shared/src/main/scala/org/specs2/matcher/TaskMatchers.scala:13: error: type mismatch
  returnValue(overloaded(null: Matcher[AnyRef]))
                             ^
```

But used to sneak through compilation before:

```
    Repro#8130.this.returnValue#15559[Disj#8127[AnyRef#1934, _]](Repro#8130.this.matcherIsValueCheck#15562[Disj#8127[AnyRef#1934, _]](Repro#8130.this.overloaded#15565[AnyRef#1934](Repro#8130.this.matcherIsValueCheck#15562[AnyRef#1934]((null: org#15.specs2#6588.matcher#6594.Matcher#7354[AnyRef#1934])))))
  }
}

warning: there was one feature warning; re-run with -feature for details
one warning found
```