SI-5887: Can try any expression
Previously, parsing `try` was special-cased for expressions
beginning with paren or brace. Perhaps that was to avoid odd
sights such as `try (1,2,3)` or `try { case _ => }`, but it
also broke `try { 1 } + 1 finally ()`.

This commit takes an arbitrary expression to `try`.

It also takes an arbitrary expression for `catch`. But for
improved type safety, the expression is required to conform
to `PartialFunction[Throwable, ?]`. The previous transform
was named-based. In addition, this commit invokes `applyOrElse`.

Previously:
```
scala> try 42 catch new {
     | def isDefinedAt(x: Any) = false
     | def apply(x: Any) = ()
     | }
warning: there was one feature warning; re-run with -feature for details
res0: AnyVal = 42

scala> try 42 catch 22
<console>:8: error: value isDefinedAt is not a member of Int
              try 42 catch 22
                           ^
```
Now:
```
scala> try 42 catch new {
     | def isDefinedAt(x: Any) = false
     | def apply(x: Any) = ()
     | }
<console>:8: error: type mismatch;
 found   : AnyRef{}
 required: PartialFunction[Throwable,?]
              try 42 catch new {
                           ^

scala> try 42 catch 22
<console>:8: error: type mismatch;
 found   : Int(22)
 required: PartialFunction[Throwable,?]
              try 42 catch 22
                           ^
```