Removing unnecessary AnyVal code.
...since it works from source. The parser must be forcibly restrained
from adding a bogus constructor, but other than that it's pretty much
smooth sailing.  To give an idea how smooth, if I change scala.Short like so:

  trait Bippy extends Any
  final class Short extends AnyVal with Bippy

Then it just works, at least until the fiction is revealed.

  scala> def f(x: Bippy) = x
  f: (x: Bippy)Bippy

  scala> f(5)
  <console>:9: error: type mismatch;
   found   : Int(5)
   required: Bippy
                f(5)
                  ^

  scala> f(5: Short)
  java.lang.ClassCastException: java.lang.Short cannot be cast to scala.Bippy
  	at .<init>(<console>:9)
  	at .<clinit>(<console>)
  	at .<init>(<console>:11)