[nomerge] SI-10037 ASR/LSR switched in ICodeReader
Noticed when inlining from a class file.

The test doesn't work because inlining fails with
bytecode unavailable due to:
```
scala.reflect.internal.MissingRequirementError: object X in compiler mirror not found.
```