Don't infer implicits from non-accessible companion
Implicits found in the companion object of a type should not be
inferred if the companion object is not accessible.

It used to work because the compiler calls `makeNotPrivate` on the
companion, but in separate compilation that could result in a
`NoSuchMethodError` at runtime.