Revert "SI-8253 Fix incorrect parsing of <elem xmlns={f("a")}/>"
This reverts commit 8d175b907d41323333a5613e419303f10beddc76.

This commit broke compilation of the test suite of scala-xml:

```
[error] /localhome/jenkins/c/workspace/scala-release-2.11.x/scala-xml/src/test/scala/scala/xml/XMLTest.scala:604: type mismatch;
[error]  found   : scala.xml.Text
[error]  required: String
[error]     <wsdl:definitions name={ serviceName } xmlns:tns={ Text("target3") }>
[error]                                                            ^
[error] one error found
[error] (test:compile) Compilation failed
```

I have moved the tests to pending, rather than deleting them.