Fix and extend Array.apply varargs optimization
The existing optimization for `Array.apply[T]` overreaches by
assuming that the `ArrayValue` carrying the varargs will have the
same element type as the implicit class tag. However, this is
not the case when the type argument is a generic type:

```
scala> def foo[T <: AnyRef : reflect.ClassTag](t: T) = Array.apply[T](t); foo[String]("")
java.lang.ClassCastException: [Ljava.lang.Object; cannot be cast to [Ljava.lang.String;
  ... 32 elided
```

This PR limits the existing optimization to cases where:

  - The class tag is an implicit arg
  - The class tag is materialized (not found via normal implicit search)

The second criterion excludes the call above.

A new, fallback optimization is provided that avoids a temporary
array and collection wrapper by emitting:

```
val arr = classTag.newArray(N)
ScalaRunTime.arrayUpdate(arr, N, elemN)
...
arr
}
```