SI-10067 Java defined inner classes don't have outer accessors
If we pretend they do, we can walk into NoSuchMethodErrors when
translating type patterns path dependent types.

This commit avoids this symptom by changing the explicitouter
info transformer. A following commit will change the pattern
matcher itself to avoid speculatively adding this outer check
that will be always dropped in explicitouter.