add test case for t8431
fixed since Scala 2.12

```
Welcome to Scala 2.11.12 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_181).
Type in expressions for evaluation. Or try :help.

scala> import scala.{ specialized => spec }
import scala.{specialized=>spec}

scala> trait EqProductFoo[@spec(Int) A] {
     |   def eqv(x0: A): Boolean = true
     | }
defined trait EqProductFoo

scala> trait OrderProductFoo[@spec(Int) A] extends EqProductFoo[A] {
     |   override def eqv(x0: A): Boolean = super.eqv(x0)
     | }
defined trait OrderProductFoo

scala> class C extends OrderProductFoo[Int]
defined class C

scala> val c = new C
java.lang.ClassFormatError: Duplicate method name "super$eqv$mcI$sp" with signature "(I)Z" in class file C
  at java.lang.ClassLoader.defineClass1(Native Method)
  at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
  at scala.reflect.internal.util.AbstractFileClassLoader.findClass(AbstractFileClassLoader.scala:64)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
  at java.lang.Class.getDeclaredMethods0(Native Method)
  at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
  at java.lang.Class.privateGetPublicMethods(Class.java:2902)
  at java.lang.Class.getMethods(Class.java:1615)
  at scala.tools.nsc.interpreter.IMain$ReadEvalPrint.evalMethod(IMain.scala:855)
  at scala.tools.nsc.interpreter.IMain$ReadEvalPrint.call(IMain.scala:788)
  at scala.tools.nsc.interpreter.IMain$Request.loadAndRun(IMain.scala:1054)
  at scala.tools.nsc.interpreter.IMain$WrappedRequest$$anonfun$loadAndRunReq$1.apply(IMain.scala:645)
  at scala.tools.nsc.interpreter.IMain$WrappedRequest$$anonfun$loadAndRunReq$1.apply(IMain.scala:644)
  at scala.reflect.internal.util.ScalaClassLoader$class.asContext(ScalaClassLoader.scala:31)
  at scala.reflect.internal.util.AbstractFileClassLoader.asContext(AbstractFileClassLoader.scala:19)
  at scala.tools.nsc.interpreter.IMain$WrappedRequest.loadAndRunReq(IMain.scala:644)
  at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:576)
  at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:572)
  at scala.tools.nsc.interpreter.ILoop.interpretStartingWith(ILoop.scala:819)
  at scala.tools.nsc.interpreter.ILoop.command(ILoop.scala:691)
  at scala.tools.nsc.interpreter.ILoop.processLine(ILoop.scala:404)
  at scala.tools.nsc.interpreter.ILoop.loop(ILoop.scala:425)
  at scala.tools.nsc.interpreter.ILoop$$anonfun$process$1.apply$mcZ$sp(ILoop.scala:993)
  at scala.tools.nsc.interpreter.ILoop$$anonfun$process$1.apply(ILoop.scala:891)
  at scala.tools.nsc.interpreter.ILoop$$anonfun$process$1.apply(ILoop.scala:891)
  at scala.reflect.internal.util.ScalaClassLoader$.savingContextLoader(ScalaClassLoader.scala:97)
  at scala.tools.nsc.interpreter.ILoop.process(ILoop.scala:891)
  at scala.tools.nsc.MainGenericRunner.runTarget$1(MainGenericRunner.scala:74)
  at scala.tools.nsc.MainGenericRunner.run$1(MainGenericRunner.scala:87)
  at scala.tools.nsc.MainGenericRunner.process(MainGenericRunner.scala:98)
  at scala.tools.nsc.MainGenericRunner$.main(MainGenericRunner.scala:103)
  at scala.tools.nsc.MainGenericRunner.main(MainGenericRunner.scala)
```

```
Welcome to Scala 2.12.0 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_181).
Type in expressions for evaluation. Or try :help.

scala> import scala.{ specialized => spec }
import scala.{specialized=>spec}

scala> trait EqProductFoo[@spec(Int) A] {
     |   def eqv(x0: A): Boolean = true
     | }
defined trait EqProductFoo

scala> trait OrderProductFoo[@spec(Int) A] extends EqProductFoo[A] {
     |   override def eqv(x0: A): Boolean = super.eqv(x0)
     | }
defined trait OrderProductFoo

scala> class C extends OrderProductFoo[Int]
defined class C

scala> val c = new C
c: C = C@732c9b5c

scala> c.eqv(42)
res0: Boolean = true
```

```
Welcome to Scala 2.13.0-M4 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_181).
Type in expressions for evaluation. Or try :help.

scala> import scala.{ specialized => spec }
import scala.{specialized=>spec}

scala> trait EqProductFoo[@spec(Int) A] {
     |   def eqv(x0: A): Boolean = true
     | }
defined trait EqProductFoo

scala> trait OrderProductFoo[@spec(Int) A] extends EqProductFoo[A] {
     |   override def eqv(x0: A): Boolean = super.eqv(x0)
     | }
defined trait OrderProductFoo

scala> class C extends OrderProductFoo[Int]
defined class C

scala> val c = new C
c: C = C@781654f8

scala> c.eqv(42)
res0: Boolean = true
```