recompiled msil.jar (fix problem: NoSuchMethodE...
recompiled msil.jar (fix problem: NoSuchMethodError:
scala.runtime.StringAdd.$plus(Ljava/lang/String;)Ljava/lang/String
introduced with r15166)