Modified erasure so we have enough information ...
Modified erasure so we have enough information to determine whether we
need to use scala or java erasure semantics. This fixes the runtime
failure illustrated here:

  % scala29 -e 'java.util.Collections.max(null)'
  java.lang.NoSuchMethodError: java.util.Collections.max(Ljava/util/Collection;)Ljava/lang/Comparable;

Review by odersky.