Require types to be conformant for eta-expansion of SAM under -Xsource:3
Ref scala bug 12006
Ref scala scala 7660

```
class C(s: java.io.InputStream); class D(u: java.net.URL) extends C(u.openStream)
```

raised in 12006 a weird piece of code under -Xsource:3 since we can interpret it in two ways.

1. `InputStream` is a SAM of `def read(): Int`, and `C(u.openStream)` requires an eta-expansion from openStream method to `() => Int`.
2. `u.openStream` needs auto application `()`.

Under -Xsource:3 Scala 2.13.2 takes the first interpretation since 7660 and then errors with surprising:

```
   error: type mismatch;
    found   : java.io.InputStream
    required: Int
```

This adds an additional check to see if the types weakly match up between `def read(): Int` and `URL#openStream` before saying yes to eta-expansion.