Further tweak version of continuations plugin in scala-dist.pom
While we must use full version, rather than the cross version
(12720e699), we need to use latest non-snapshot version.

This should avoid failures like:

  https://jenkins.scala-ide.org:8496/jenkins/view/Scala%20Xsource%20flag%20nightlies/job/Akka/63/console

Such as:

	[warn] ::::::::::::::::::::::::::::::::::::::::::::::
	[warn] ::          UNRESOLVED DEPENDENCIES         ::
	[warn] ::::::::::::::::::::::::::::::::::::::::::::::
	[warn] :: org.scala-lang.plugins#scala-continuations-plugin_2.11.0-SNAPSHOT;1.0.1:
	not found
	[warn] ::::::::::::::::::::::::::::::::::::::::::::::
	sbt.ResolveException: unresolved dependency:
	org.scala-lang.plugins#scala-continuations-plugin_2.11.0-SNAPSHOT;1.0.1: