Various fixes for sbt 1.2 upgrade
1. Adapt to renaming of ivyScala

2. Be less intrusive with customization of baseDirectory

In our attempt to make forked project take on the working directory
of the root project, rather than of their module, we ended up
causing a clash in the directory used by the incremental compiler
to backup classfiles, which uses a value relative to that base.

The symptom was an intermitten error such as:

```
[error] ## Exception when compiling 0 sources to /Users/jz/code/scala-sbt-1/target/partest-extras/test-classes
[error] Could not create directory /Users/jz/code/scala-sbt-1/target/scala-2.13.0-M3/classes.bak
```

This commit adjusts ForkOptions instead to more directly
achieve our goal.

3. Heed deprecation warning in ScalaInstance tweak

4. Disable finding sources files in project base

Something has changed in SBT 1.x, and our attempt to clear the
sources for scalacheck/compile: weren't successful:

```
sbt:root> show scalacheck / Compile / unmanagedSources
[info] * /Users/jz/code/scala/test/scalacheck/array-new.scala
[info] * /Users/jz/code/scala/test/scalacheck/array-old.scala
[info] * /Users/jz/code/scala/test/scalacheck/CheckCollections.scala
[info] * /Users/jz/code/scala/test/scalacheck/CheckEither.scala
```

What changed? 4502348a12c, earlier in this PR, removed our override
of `baseDirectory`. So sub-projects now have their own sub-directory
as the base (which is the standard SBT behaviour). If these include
source files directly, as is the case with `./test/scalacheck`, these
would be included by virtue of the long standing SBT behaviour to
let you skip the hassle of source directories for toy projects.

This commit disables that behaviour with `sourcesInBase := false`

5. Fixup OSGi test suite after baseDirectory change

6. Let SBT add api.url to the POM

Since https://github.com/sbt/sbt/pull/2262, we don't need to do this.
And attempting to do it results in duplicate properties in the POM file,
which doesn't pass POM validation by artifactory.

7. Use the recommended, and working, `sbt -warn`

In favour of `--warn`, which is broken in SBT 1.x.

Early commands are ones that are run before project load, in this case,
`-warn` used to mean `-` (schedule early) and `warn` (the command to
change log level)`.

`sbt-extras` translates its `-w` option into `--warn`, or passes through
`--warn` if provided. The official SBT launcher passes through `--warn`.

`sbt -warn` still works in 1.x, but `sbt --warn` doesn't give the non-zero
error code after a failure.

```
for sbt in 0.13.17 1.1.4; do for opt in "--warn" "-warn"; do (set -x; java -jar /home/jenkins/.sbt/launchers/0.13.17/sbt-launch.jar -Dsbt.version=$sbt $opt 'eval ???'; echo $?;) done; done
+ java -jar /home/jenkins/.sbt/launchers/0.13.17/sbt-launch.jar -Dsbt.version=0.13.17 --warn 'eval ???'
scala.NotImplementedError: an implementation is missing
    at scala.Predef$.$qmark$qmark$qmark(Predef.scala:252)
...
[error] scala.NotImplementedError: an implementation is missing
[error] Use 'last' for the full log.
+ echo 1
1
+ java -jar /home/jenkins/.sbt/launchers/0.13.17/sbt-launch.jar -Dsbt.version=0.13.17 -warn 'eval ???'
scala.NotImplementedError: an implementation is missing
    at scala.Predef$.$qmark$qmark$qmark(Predef.scala:252)
...
[error] scala.NotImplementedError: an implementation is missing
[error] Use 'last' for the full log.
+ echo 1
1
+ java -jar /home/jenkins/.sbt/launchers/0.13.17/sbt-launch.jar -Dsbt.version=1.1.4 --warn 'eval ???'
[warn] sbt version mismatch, current: 1.1.4, in build.properties: "0.13.17", use 'reboot' to use the new value.
[info] Loading project definition from /tmp/scratch/project
[info] Updating ProjectRef(uri("file:/tmp/scratch/project/"), "scratch-build")...
[info] Done updating.
[info] Set current project to scratch (in build file:/tmp/scratch/)
[warn] The `-` command is deprecated in favor of `onFailure` and will be removed in a later version
[error] scala.NotImplementedError: an implementation is missing
[error]     at scala.Predef$.$qmark$qmark$qmark(Predef.scala:284)
..
[error] scala.NotImplementedError: an implementation is missing
[error] Use 'last' for the full log.
+ echo 0
0
+ java -jar /home/jenkins/.sbt/launchers/0.13.17/sbt-launch.jar -Dsbt.version=1.1.4 -warn 'eval ???'
+ echo 1
1
```

This commits changes our scripts to use the recommended `-warn`. However,
I'd say that SBT 1.x should either reject `--warn` outright or be compatible
with the old behaviour.