Test defect for reflection of private fields
Test case, FieldAccessTest.testFieldAccess, would throw the error:

scala.ScalaReflectionException: Scala field x isn't represented as a
  Java field, neither it has a Java accessor method note that private
  parameters of class constructors don't get mapped onto fields
  and/or accessors, unless they are used outside of their declaring
  constructors.

Test case, OpenHashMapTest.maintainsDeletedCount couldn't be updated
with scala-reflect.